#declaring the type of language
language: python
   
#declaring the versions of the language specified above  you to want the test the code against
python:
  - "3.6"
   
#before executing the code installing the dependencies if any
install:
  - pip install -r requirements.txt
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar zxvf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib
  - ./configure --prefix="/usr"
  - make
  - sudo make install
  - pip install ta-lib
  - cd ..
   
#running the desired code file for testing your code
script:
  - python analysis.py
  - git config --global user.email "victorgau@gmail.com"
  - git config --global user.name "Victor Gau"
  - git add docs/*.html
  - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  - git remote add origin https://${GH_TOKEN}@github.com/victorgau/MultiStrategies.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin master 